<b> Loading the libraries

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [5]:
df.dropna(inplace=True)
df.isnull().sum()


survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

<b> One hot encoding

In [6]:
df['Sex' ] = pd.get_dummies( data =df.sex , drop_first=True )

In [7]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1          1       1  female  38.0      1      0  71.2833        C  First   
3          1       1  female  35.0      1      0  53.1000        S  First   
6          0       1    male  54.0      0      0  51.8625        S  First   
10         1       3  female   4.0      1      1  16.7000        S  Third   
11         1       1  female  58.0      0      0  26.5500        S  First   

      who  adult_male deck  embark_town alive  alone  Sex  
1   woman       False    C    Cherbourg   yes  False    0  
3   woman       False    C  Southampton   yes  False    0  
6     man        True    E  Southampton    no   True    1  
10  child       False    G  Southampton   yes  False    0  
11  woman       False    C  Southampton   yes   True    0

<b>Converting the entire column

In [10]:
no_dummy_data = pd.get_dummies(data =df)
no_dummy_data

survived  pclass   age  sibsp  parch     fare  adult_male  alone  Sex  \
1           1       1  38.0      1      0  71.2833       False  False    0   
3           1       1  35.0      1      0  53.1000       False  False    0   
6           0       1  54.0      0      0  51.8625        True   True    1   
10          1       3   4.0      1      1  16.7000       False  False    0   
11          1       1  58.0      0      0  26.5500       False   True    0   
..        ...     ...   ...    ...    ...      ...         ...    ...  ...   
871         1       1  47.0      1      1  52.5542       False  False    0   
872         0       1  33.0      0      0   5.0000        True   True    1   
879         1       1  56.0      0      1  83.1583       False  False    0   
887         1       1  19.0      0      0  30.0000       False   True    0   
889         1       1  26.0      0      0  30.0000        True   True    1   

     sex_female  ...  deck_C  deck_D  deck_E  deck_F  deck_G  \
1             1  ...       1       0       0       0       0   
3             1  ...       1       0       0       0       0   
6             0  ...       0       0       1       0       0   
10            1  ...       0       0       0       0       1   
11            1  ...       1       0       0       0       0   
..          ...  ...     ...     ...     ...     ...     ...   
871           1  ...       0       1       0       0       0   
872           0  ...       0       0       0       0       0   
879           1  ...       1       0       0       0       0   
887           1  ...       0       0       0       0       0   
889           0  ...       1       0       0       0       0   

     embark_town_Cherbourg  embark_town_Queenstown  embark_town_Southampton  \
1                        1                       0                        0   
3                        0                       0                        1   
6                        0                       0                        1   
10                       0                       0                        1   
11                       0                       0                        1   
..                     ...                     ...                      ...   
871                      0                       0                        1   
872                      0                       0                        1   
879                      1                       0                        0   
887                      0                       0                        1   
889                      1                       0                        0   

     alive_no  alive_yes  
1           0          1  
3           0          1  
6           1          0  
10          0          1  
11          0          1  
..        ...        ...  
871         0          1  
872         1          0  
879         0          1  
887         0          1  
889         0          1  

[182 rows x 32 columns]

In [12]:
dummy_df = pd.get_dummies( data =df , drop_first = True)
dummy_df

survived  pclass   age  sibsp  parch     fare  adult_male  alone  Sex  \
1           1       1  38.0      1      0  71.2833       False  False    0   
3           1       1  35.0      1      0  53.1000       False  False    0   
6           0       1  54.0      0      0  51.8625        True   True    1   
10          1       3   4.0      1      1  16.7000       False  False    0   
11          1       1  58.0      0      0  26.5500       False   True    0   
..        ...     ...   ...    ...    ...      ...         ...    ...  ...   
871         1       1  47.0      1      1  52.5542       False  False    0   
872         0       1  33.0      0      0   5.0000        True   True    1   
879         1       1  56.0      0      1  83.1583       False  False    0   
887         1       1  19.0      0      0  30.0000       False   True    0   
889         1       1  26.0      0      0  30.0000        True   True    1   

     sex_male  ...  who_woman  deck_B  deck_C  deck_D  deck_E  deck_F  deck_G  \
1           0  ...          1       0       1       0       0       0       0   
3           0  ...          1       0       1       0       0       0       0   
6           1  ...          0       0       0       0       1       0       0   
10          0  ...          0       0       0       0       0       0       1   
11          0  ...          1       0       1       0       0       0       0   
..        ...  ...        ...     ...     ...     ...     ...     ...     ...   
871         0  ...          1       0       0       1       0       0       0   
872         1  ...          0       1       0       0       0       0       0   
879         0  ...          1       0       1       0       0       0       0   
887         0  ...          1       1       0       0       0       0       0   
889         1  ...          0       0       1       0       0       0       0   

     embark_town_Queenstown  embark_town_Southampton  alive_yes  
1                         0                        0          1  
3                         0                        1          1  
6                         0                        1          0  
10                        0                        1          1  
11                        0                        1          1  
..                      ...                      ...        ...  
871                       0                        1          1  
872                       0                        1          0  
879                       0                        0          1  
887                       0                        1          1  
889                       0                        0          1  

[182 rows x 25 columns]

In [13]:
dummy_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182 entries, 1 to 889
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   survived                 182 non-null    int64  
 1   pclass                   182 non-null    int64  
 2   age                      182 non-null    float64
 3   sibsp                    182 non-null    int64  
 4   parch                    182 non-null    int64  
 5   fare                     182 non-null    float64
 6   adult_male               182 non-null    bool   
 7   alone                    182 non-null    bool   
 8   Sex                      182 non-null    uint8  
 9   sex_male                 182 non-null    uint8  
 10  embarked_Q               182 non-null    uint8  
 11  embarked_S               182 non-null    uint8  
 12  class_Second             182 non-null    uint8  
 13  class_Third              182 non-null    uint8  
 14  who_man                  1

In [70]:
from sklearn.preprocessing import  MinMaxScaler, RobustScaler,LabelEncoder, StandardScaler

<b> Label Encoder

In [71]:
lee = LabelEncoder()

In [72]:
df['Embarked'] = lee.fit_transform( df.embarked)
df

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
6           0       1    male  54.0      0      0  51.8625        S  First   
10          1       3  female   4.0      1      1  16.7000        S  Third   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
871         1       1  female  47.0      1      1  52.5542        S  First   
872         0       1    male  33.0      0      0   5.0000        S  First   
879         1       1  female  56.0      0      1  83.1583        C  First   
887         1       1  female  19.0      0      0  30.0000        S  First   
889         1       1    male  26.0      0      0  30.0000        C  First   

       who  adult_male deck  embark_town alive  alone  Sex  Embarked  Class  \
1    woman       False    C    Cherbourg   yes  False    0         0      0   
3    woman       False    C  Southampton   yes  False    0         2      0   
6      man        True    E  Southampton    no   True    1         2      0   
10   child       False    G  Southampton   yes  False    0         2      2   
11   woman       False    C  Southampton   yes   True    0         2      0   
..     ...         ...  ...          ...   ...    ...  ...       ...    ...   
871  woman       False    D  Southampton   yes  False    0         2      0   
872    man        True    B  Southampton    no   True    1         2      0   
879  woman       False    C    Cherbourg   yes  False    0         0      0   
887  woman       False    B  Southampton   yes   True    0         2      0   
889    man        True    C    Cherbourg   yes   True    1         0      0   

     Who       Age  
1      2  0.468892  
3      2  0.430956  
6      1  0.671219  
10     0  0.038948  
11     2  0.721801  
..   ...       ...  
871    2  0.582701  
872    1  0.405665  
879    2  0.696510  
887    2  0.228629  
889    1  0.317147  

[182 rows x 20 columns]

In [73]:
df.Embarked.unique()

array([0, 2, 1])

In [74]:
df['Class'] = lee.fit_transform(df['class'])
df.Class.unique()

array([0, 2, 1])

In [75]:
df['Who'] = lee.fit_transform(df.who)
df.Who.unique()

array([2, 1, 0])

<b> MINMAX Scaler

In [76]:
mima = MinMaxScaler()

In [77]:
df[['age']]

age
1    38.0
3    35.0
6    54.0
10    4.0
11   58.0
..    ...
871  47.0
872  33.0
879  56.0
887  19.0
889  26.0

[182 rows x 1 columns]

In [78]:
age =df[['age']].values

In [79]:
age

array([[38.  ],
       [35.  ],
       [54.  ],
       [ 4.  ],
       [58.  ],
       [34.  ],
       [28.  ],
       [19.  ],
       [49.  ],
       [65.  ],
       [45.  ],
       [29.  ],
       [25.  ],
       [23.  ],
       [46.  ],
       [71.  ],
       [23.  ],
       [21.  ],
       [47.  ],
       [24.  ],
       [32.5 ],
       [54.  ],
       [19.  ],
       [37.  ],
       [24.  ],
       [36.5 ],
       [22.  ],
       [61.  ],
       [56.  ],
       [50.  ],
       [ 1.  ],
       [ 3.  ],
       [44.  ],
       [58.  ],
       [ 2.  ],
       [40.  ],
       [31.  ],
       [32.  ],
       [38.  ],
       [35.  ],
       [44.  ],
       [37.  ],
       [29.  ],
       [62.  ],
       [30.  ],
       [52.  ],
       [40.  ],
       [58.  ],
       [35.  ],
       [37.  ],
       [63.  ],
       [19.  ],
       [36.  ],
       [ 2.  ],
       [50.  ],
       [ 0.92],
       [17.  ],
       [30.  ],
       [24.  ],
       [18.  ],
       [31.  ],
       [40.  ],
       [

In [80]:
df['Age'] =mima.fit_transform(age)

In [81]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
6           0       1    male  54.0      0      0  51.8625        S  First   
10          1       3  female   4.0      1      1  16.7000        S  Third   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
871         1       1  female  47.0      1      1  52.5542        S  First   
872         0       1    male  33.0      0      0   5.0000        S  First   
879         1       1  female  56.0      0      1  83.1583        C  First   
887         1       1  female  19.0      0      0  30.0000        S  First   
889         1       1    male  26.0      0      0  30.0000        C  First   

       who  adult_male deck  embark_town alive  alone  Sex  Embarked  Class  \
1    woman       False    C    Cherbourg   yes  False    0         0      0   
3    woman       False    C  Southampton   yes  False    0         2      0   
6      man        True    E  Southampton    no   True    1         2      0   
10   child       False    G  Southampton   yes  False    0         2      2   
11   woman       False    C  Southampton   yes   True    0         2      0   
..     ...         ...  ...          ...   ...    ...  ...       ...    ...   
871  woman       False    D  Southampton   yes  False    0         2      0   
872    man        True    B  Southampton    no   True    1         2      0   
879  woman       False    C    Cherbourg   yes  False    0         0      0   
887  woman       False    B  Southampton   yes   True    0         2      0   
889    man        True    C    Cherbourg   yes   True    1         0      0   

     Who       Age  
1      2  0.468892  
3      2  0.430956  
6      1  0.671219  
10     0  0.038948  
11     2  0.721801  
..   ...       ...  
871    2  0.582701  
872    1  0.405665  
879    2  0.696510  
887    2  0.228629  
889    1  0.317147  

[182 rows x 20 columns]

In [82]:
df.Age.min()

0.0

In [83]:
df.Age.max()

1.0

<b> Standard Scalar

In [85]:
ss = StandardScaler()

In [89]:
fare = df[['fare']].values

In [93]:
fare

array([[ 71.2833],
       [ 53.1   ],
       [ 51.8625],
       [ 16.7   ],
       [ 26.55  ],
       [ 13.    ],
       [ 35.5   ],
       [263.    ],
       [ 76.7292],
       [ 61.9792],
       [ 83.475 ],
       [ 10.5   ],
       [  7.65  ],
       [263.    ],
       [ 61.175 ],
       [ 34.6542],
       [ 63.3583],
       [ 77.2875],
       [ 52.    ],
       [247.5208],
       [ 13.    ],
       [ 77.2875],
       [ 26.2833],
       [ 53.1   ],
       [ 79.2   ],
       [ 26.    ],
       [ 66.6   ],
       [ 33.5   ],
       [ 30.6958],
       [ 28.7125],
       [ 39.    ],
       [ 26.    ],
       [ 27.7208],
       [146.5208],
       [ 10.4625],
       [ 31.    ],
       [113.275 ],
       [ 76.2917],
       [ 90.    ],
       [ 83.475 ],
       [ 90.    ],
       [ 52.5542],
       [ 10.4625],
       [ 26.55  ],
       [ 86.5   ],
       [ 79.65  ],
       [  0.    ],
       [153.4625],
       [135.6333],
       [ 29.7   ],
       [ 77.9583],
       [ 91.0792],
       [ 12.

In [101]:
df['Age'] = ss.fit_transform(age)
df

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
6           0       1    male  54.0      0      0  51.8625        S  First   
10          1       3  female   4.0      1      1  16.7000        S  Third   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
871         1       1  female  47.0      1      1  52.5542        S  First   
872         0       1    male  33.0      0      0   5.0000        S  First   
879         1       1  female  56.0      0      1  83.1583        C  First   
887         1       1  female  19.0      0      0  30.0000        S  First   
889         1       1    male  26.0      0      0  30.0000        C  First   

       who  ...  deck  embark_town alive  alone  Sex  Embarked  Class  Who  \
1    woman  ...     C    Cherbourg   yes  False    0         0      0    2   
3    woman  ...     C  Southampton   yes  False    0         2      0    2   
6      man  ...     E  Southampton    no   True    1         2      0    1   
10   child  ...     G  Southampton   yes  False    0         2      2    0   
11   woman  ...     C  Southampton   yes   True    0         2      0    2   
..     ...  ...   ...          ...   ...    ...  ...       ...    ...  ...   
871  woman  ...     D  Southampton   yes  False    0         2      0    2   
872    man  ...     B  Southampton    no   True    1         2      0    1   
879  woman  ...     C    Cherbourg   yes  False    0         0      0    2   
887  woman  ...     B  Southampton   yes   True    0         2      0    2   
889    man  ...     C    Cherbourg   yes   True    1         0      0    1   

          Age      Fare  
1    0.152082 -0.100110  
3   -0.039875 -0.338485  
6    1.175852 -0.354708  
10  -2.023430 -0.815672  
11   1.431795 -0.686543  
..        ...       ...  
871  0.727953 -0.345640  
872 -0.167846 -0.969053  
879  1.303824  0.055566  
887 -1.063646 -0.641315  
889 -0.615746 -0.641315  

[182 rows x 21 columns]

In [102]:
df.Age.min()

-2.220506254820847

In [103]:
df.Age.max()

2.8394796068956767

<b> Robust Scalar

In [104]:
rc = RobustScaler()

In [105]:
df['Age1'] = rc.fit_transform(age)

In [107]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1          1       1  female  38.0      1      0  71.2833        C  First   
3          1       1  female  35.0      1      0  53.1000        S  First   
6          0       1    male  54.0      0      0  51.8625        S  First   
10         1       3  female   4.0      1      1  16.7000        S  Third   
11         1       1  female  58.0      0      0  26.5500        S  First   

      who  ...  embark_town alive  alone Sex  Embarked  Class  Who       Age  \
1   woman  ...    Cherbourg   yes  False   0         0      0    2  0.152082   
3   woman  ...  Southampton   yes  False   0         2      0    2 -0.039875   
6     man  ...  Southampton    no   True   1         2      0    1  1.175852   
10  child  ...  Southampton   yes  False   0         2      2    0 -2.023430   
11  woman  ...  Southampton   yes   True   0         2      0    2  1.431795   

        Fare      Age1  
1  -0.100110  0.084211  
3  -0.338485 -0.042105  
6  -0.354708  0.757895  
10 -0.815672 -1.347368  
11 -0.686543  0.926316  

[5 rows x 22 columns]

In [108]:
df.Age1.max()

1.8526315789473684

In [109]:
df.Age1.min()

-1.4770526315789474